### PR TITLE
code cleanup. fix type mistmatch. simplify & speedify. revert rapidjson NOT for android

### PR DESCRIPTION
**Pull request by tigrazone**

### CODE REVIEW

**Comment by gameknife** [comment]
the roughness change to more powerful, I see that ONB and GGX Sampling is tweaked, is currently the right one?

**Comment by gameknife** [comment]
> the roughness change to more powerful, I see that ONB and GGX Sampling is tweaked, is currently the right one?

seems the previous roughness is always wrong, currently is the right one... I will adjust some materials in example scenes

**Comment by tigrazone** [comment]
> the roughness change to more powerful, I see that ONB and GGX Sampling is tweaked, is currently the right one?

I read sources of nvpro_core and take many talks with devs and understand more right ways. Also I use clang with Visual Studio and this compiler show me errors. Also I get your last release to rework to my version of gkNextRender and I see types mismatch in materialId and some places where uint is ok but you use int.
Also * 0.0 I change to assignment 0.0 to variable.
Offset = offset + something I chsnge to
Offset += something and so.

My version of your renderer use accumulate, rgba32f, open file by nativefiledialog-extended, gltf and glb, pack vertex data - I use 6 uints/floats vs your 9. Also in my version I use hdris file name select dropdown vs your change number...

**Comment by tigrazone** [comment]
Some of my talks with authors of nvpro_core
https://github.com/nvpro-samples/nvpro_core/issues/68
https://github.com/nvpro-samples/nvpro_core/issues/66
https://github.com/nvpro-samples/nvpro_core/issues/63
https://github.com/nvpro-samples/nvpro_core/issues/62
These talks make me some understanding in themes which I understand wrong and change of Mix() in your renderer is minimize of * for example

**Comment by gameknife** [comment]
> > the roughness change to more powerful, I see that ONB and GGX Sampling is tweaked, is currently the right one?
> 
> I read sources of nvpro_core and take many talks with devs and understand more right ways. Also I use clang with Visual Studio and this compiler show me errors. Also I get your last release to rework to my version of gkNextRender and I see types mismatch in materialId and some places where uint is ok but you use int. Also * 0.0 I change to assignment 0.0 to variable. Offset = offset + something I chsnge to Offset += something and so.
> 
> My version of your renderer use accumulate, rgba32f, open file by nativefiledialog-extended, gltf and glb, pack vertex data - I use 6 uints/floats vs your 9. Also in my version I use hdris file name select dropdown vs your change number...

didn't see the 6 floats pack in your forked repo, did you packed normal, texcoord, matid into 3 dword? it will down the memory bandwidth, did that help performance on raytracing?

**Comment by tigrazone** [comment]
> > > the roughness change to more powerful, I see that ONB and GGX Sampling is tweaked, is currently the right one?
> > 
> > 
> > I read sources of nvpro_core and take many talks with devs and understand more right ways. Also I use clang with Visual Studio and this compiler show me errors. Also I get your last release to rework to my version of gkNextRender and I see types mismatch in materialId and some places where uint is ok but you use int. Also * 0.0 I change to assignment 0.0 to variable. Offset = offset + something I chsnge to Offset += something and so.
> > My version of your renderer use accumulate, rgba32f, open file by nativefiledialog-extended, gltf and glb, pack vertex data - I use 6 uints/floats vs your 9. Also in my version I use hdris file name select dropdown vs your change number...
> 
> didn't see the 6 floats pack in your forked repo, did you packed normal, texcoord, matid into 3 dword? it will down the memory bandwidth, did that help performance on raytracing?

I push to fork all I want to share. You dont support all my proposes and I do it in my private repo
This is how I make Vertex smaller
compact-vertex

on c++ side
vertex-be

[compress.glsl](https://github.com/nvpro-samples/vk_raytrace/blob/master/shaders/compress.glsl)
compress_normal_cpp.h is c++ version of compress.glsl for compress normals

**Comment by tigrazone** [comment]
> it will down the memory bandwidth, did that help performance on raytracing?

It use smaller memory amount and unpacking dont use too much time.
Added to compress.glsl:
#define F16VEC2 f16vec2
#extension GL_EXT_shader_16bit_storage : require
#extension GL_EXT_shader_explicit_arithmetic_types_float16 : require

on c++ side
#define F16VEC2 u16vec2

This approach with f16vec2/u16vec2 I found in older builds of https://github.com/spnda/vk_gltf_viewer

https://github.com/spnda/vk_gltf_viewer/blob/6025254d65fc1f981ca2313bb07b5dbf4afb5d76/src/main.cpp#L993C1-L996C7

**Pull request merged**
