### PR TITLE
fix texture map

### PR DESCRIPTION
**Pull request by tigrazone**

### CODE REVIEW

**Comment by tigrazone** [comment]
Need to work more... I plan to add command line option --load-scene for obj, glb, gltf files.
False start. I make pull request after finish these feature

**Comment by tigrazone** [comment]
Did you know how to understand which type of material w/o faking like check material name to "glass" string variants?

**Comment by gameknife** [comment]
obj file is hard to impl pbr material, try use gltf
if u want to edit, I can provide the source art .blend file in another repo
actually, I plan to remove obj support...

**Comment by tigrazone** [comment]
Thank you. Understand

**Comment by tigrazone** [comment]
Let it be but wrong materials is not our problem ;-)

**Pull request closed without merging**
